import React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import moment from "moment";
import { sessionDetail } from "../medical-agent/[sessionId]/page";

type Props = {
  record: sessionDetail;
};

export default function ViewReportDialog({ record }: Props) {
  const hasChiefComplaint =
    record.chiefComplaint && record.chiefComplaint.trim() !== "";
  const hasSymptoms = record.symptoms && record.symptoms.length > 0;

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" size="sm">
          View Report
        </Button>
      </DialogTrigger>

      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto p-6">
        <DialogHeader className="mb-6">
          <DialogTitle className="text-center text-2xl font-bold">
            🩺 Medical AI Voice Agent Report
          </DialogTitle>
        </DialogHeader>

        {/* Session Info */}
        <section className="mb-6">
          <h2 className="font-semibold text-blue-600 text-lg mb-2">
            Session Info
          </h2>
          <div className="grid grid-cols-2 gap-y-1 text-sm">
            <p>
              <span className="font-semibold">Doctor: </span>
              {record.selectedDoctor?.specialist || "General Physician"}
            </p>
            <p>
              <span className="font-semibold">User: </span>Anonymous
            </p>
            <p>
              <span className="font-semibold">Consulted On: </span>
              {moment(record.createdOn).format("MMMM Do YYYY, h:mm a")}
            </p>
            <p>
              <span className="font-semibold">Agent: </span>
              Medical AI Assistant
            </p>
          </div>
        </section>

        {/* Chief Complaint */}
        <section className="mb-6">
          <h2 className="font-semibold text-blue-600 text-lg mb-1">
            Chief Complaint
          </h2>
          <p className="leading-relaxed text-sm">
            {hasChiefComplaint
              ? record.chiefComplaint
              : "The user did not clearly state a chief complaint in this interaction."}
          </p>
        </section>

        {/* Summary */}
        <section className="mb-6">
          <h2 className="font-semibold text-blue-600 text-lg mb-1">Summary</h2>
          <p className="leading-relaxed text-sm">
            {record.sessionSummary ||
              "The AI medical assistant interacted with the user, but no detailed summary was recorded."}
          </p>
        </section>

        {/* Symptoms */}
        <section className="mb-6">
          <h2 className="font-semibold text-blue-600 text-lg mb-1">Symptoms</h2>
          {hasSymptoms ? (
            <ul className="list-disc ml-6 text-sm">
              {record.symptoms!.map((symptom, index) => (
                <li key={index}>{symptom}</li>
              ))}
            </ul>
          ) : (
            <p className="text-sm">No symptoms documented.</p>
          )}
        </section>

        {/* Duration & Severity */}
        <section className="mb-2">
          <h2 className="font-semibold text-blue-600 text-lg mb-1">
            Duration & Severity
          </h2>
          <div className="space-y-1 text-sm">
            <p>
              <span className="font-semibold">Duration: </span>
              {record.duration || "Not specified"}
            </p>
            <p>
              <span className="font-semibold">Severity: </span>
              {record.severity || "Not specified"}
            </p>
          </div>
        </section>

        <p className="text-xs text-gray-500 mt-6 text-center">
          This report was generated by an AI Medical Assistant for informational
          purposes only.
        </p>
      </DialogContent>
    </Dialog>
  );
}
